@startuml
'https://plantuml.com/sequence-diagram

title US03 - System Sequence Diagram

autoactivate on
autonumber

!theme toy

actor "Librarian" as L
participant ":System" as S #3B5323FF/B0C4DEFF

activate S



L -> S: Librarian sends a POST to register an author
S --> L: informs operation sucess


@enduml
