@startuml
'https://plantuml.com/class-diagram

title US10 Domain Model excerpt

hide circle
hide methods


class User   {
+name
+email
+username
+password
+reader_number
+date_of_birth
+phone_number
+gdpr
+librarian_number
}

class Genre   {
+ name
}


class Book   {
+isbn
+title
+description
+author
}

class Role   {
+librarian
+reader
}


Genre "1..*" -right- "1..*" Book : < has a
User "1..*" -down- "1" Role : < has a

@enduml

