@startuml
'https://SubscriptionServicetuml.com/class-diagram
hide circle
hide methods
title US13 Domain Model


class Book #F2AA4CFF/CE4A7EFF  {
+isbn
+title
+genre
+description
+author
}

class User #F2AA4CFF/CE4A7EFF  {
+name
+email
+role
+date_of_birth
+phone_number
+gdpr
}

class Lending #F2AA4CFF/CE4A7EFF  {
+lending_number
+librarian_number
+reader_number
+book_title
+lending_date
+return_date
+number_of_days_till_return_date
+number_of_days_in_overdue
+fine_amount
}

Book "1..*" -down- "1..*" Lending : > have
User "1..*" -down- "1..*" Lending : < has a
@enduml