@startuml
'https://plantuml.com/sequence-diagram

autonumber
title US13 System Sequence Diagram
actor "Reader" as User #F2AA4CFF/CE4A7EFF
participant ":System" as System #F2AA4CFF/CE4A7EFF

activate User

User-> System: send a GET request to have a book suggestions based on interests
System --> "User": informs operation success
@enduml