@startuml
'https://plantuml.com/sequence-diagram


autonumber
title US15 System Sequence Diagram
actor "Librarian" as User #F2AA4CFF/CE4A7EFF
participant ":System" as System #F2AA4CFF/CE4A7EFF

activate User

User-> System: send a GET request to know the average lending duration
System --> "User": informs operation success

@enduml