@startuml
'https://SubscriptionServicetuml.com/class-diagram
hide circle
hide methods
title US11 Domain Model

class User #F2AA4CFF/CE4A7EFF{
-username
readerNumber
-password
-name
-dateOfBirth
-phoneNumber
-GDPR
-role
}
class Lending #F2AA4CFF/CE4A7EFF {
-lendingNumber
-librarianNumber
-readerNumber
-bookTitle
-lendingDate
-returnDate
-number_of_days_till_return_date
-number_of_days_in_overdue
-fineAmount

}


User "1" -left-- "*" Lending




@enduml