@startuml
'https://plantuml.com/sequence-diagram

title US08 - System Sequence Diagram

autoactivate on
autonumber


actor "Librarian" as Librarian
participant ":System" as System

activate System



Librarian -> System: Librarian sends a PUT to update an book’s data
System --> Librarian: informs operation (in)sucess


@enduml
